# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /homes/sx233/t2s-os/install/bin/cmake

# The command to remove a file.
RM = /homes/sx233/t2s-os/install/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /homes/sx233/uptune

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /homes/sx233/uptune

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/homes/sx233/t2s-os/install/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/homes/sx233/t2s-os/install/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/homes/sx233/t2s-os/install/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /homes/sx233/uptune/CMakeFiles /homes/sx233/uptune/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /homes/sx233/uptune/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uptune_tests

# Build rule for target.
uptune_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uptune_tests
.PHONY : uptune_tests

# fast build rule for target.
uptune_tests/fast:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/build
.PHONY : uptune_tests/fast

src/uptune.o: src/uptune.cc.o

.PHONY : src/uptune.o

# target to build an object file
src/uptune.cc.o:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/src/uptune.cc.o
.PHONY : src/uptune.cc.o

src/uptune.i: src/uptune.cc.i

.PHONY : src/uptune.i

# target to preprocess a source file
src/uptune.cc.i:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/src/uptune.cc.i
.PHONY : src/uptune.cc.i

src/uptune.s: src/uptune.cc.s

.PHONY : src/uptune.s

# target to generate assembly for a file
src/uptune.cc.s:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/src/uptune.cc.s
.PHONY : src/uptune.cc.s

tests/cpp/test_basic.o: tests/cpp/test_basic.cc.o

.PHONY : tests/cpp/test_basic.o

# target to build an object file
tests/cpp/test_basic.cc.o:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/tests/cpp/test_basic.cc.o
.PHONY : tests/cpp/test_basic.cc.o

tests/cpp/test_basic.i: tests/cpp/test_basic.cc.i

.PHONY : tests/cpp/test_basic.i

# target to preprocess a source file
tests/cpp/test_basic.cc.i:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/tests/cpp/test_basic.cc.i
.PHONY : tests/cpp/test_basic.cc.i

tests/cpp/test_basic.s: tests/cpp/test_basic.cc.s

.PHONY : tests/cpp/test_basic.s

# target to generate assembly for a file
tests/cpp/test_basic.cc.s:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/tests/cpp/test_basic.cc.s
.PHONY : tests/cpp/test_basic.cc.s

tests/cpp/test_main.o: tests/cpp/test_main.cc.o

.PHONY : tests/cpp/test_main.o

# target to build an object file
tests/cpp/test_main.cc.o:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/tests/cpp/test_main.cc.o
.PHONY : tests/cpp/test_main.cc.o

tests/cpp/test_main.i: tests/cpp/test_main.cc.i

.PHONY : tests/cpp/test_main.i

# target to preprocess a source file
tests/cpp/test_main.cc.i:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/tests/cpp/test_main.cc.i
.PHONY : tests/cpp/test_main.cc.i

tests/cpp/test_main.s: tests/cpp/test_main.cc.s

.PHONY : tests/cpp/test_main.s

# target to generate assembly for a file
tests/cpp/test_main.cc.s:
	$(MAKE) -f CMakeFiles/uptune_tests.dir/build.make CMakeFiles/uptune_tests.dir/tests/cpp/test_main.cc.s
.PHONY : tests/cpp/test_main.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... rebuild_cache"
	@echo "... uptune_tests"
	@echo "... src/uptune.o"
	@echo "... src/uptune.i"
	@echo "... src/uptune.s"
	@echo "... tests/cpp/test_basic.o"
	@echo "... tests/cpp/test_basic.i"
	@echo "... tests/cpp/test_basic.s"
	@echo "... tests/cpp/test_main.o"
	@echo "... tests/cpp/test_main.i"
	@echo "... tests/cpp/test_main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

